schema_version = "1.0.0"

id = "vertex_weight_addon"
version = "0.0.1"
name = "Vertex Weight Viewer"
tagline = "Spine2D-style vertex weight display"
maintainer = "Xieyin"
type = "add-on"

tags = ["Mesh", "Animation"]

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-3.0-or-later",
]
